spring.application.name=login
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/login_react_spring}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
